---
title: "bmi young men"
author: "Maureen Lahiff"
date: "March 27, 2019"
output: word_document

---

# box plots, normal quantile plots, Shapiro_Wilk test
# and conf intervals and t tests for the population mean

# Baldi and Moore's BMI for adolescent men, chapter 23, n = 50

# data file is bmi_young_men.xlsx
# variable (column) name bmi

# be sure to set your working directory

```{r get libraries loaded}

source(here::here('0-setup.R'))

library(tidyverse)
library(readr)
library(readxl)
library(epiR)

```

```{r read in data}

bmi_adol_men <- read_excel(here::here("data/bmi_young_men.xlsx"), col_names = T)

```

```{r summary statistics and boxplot}

summary(bmi_adol_men$bmi)

bmi_adol_men %>% summarize(
    min = min(bmi) ,
    q1 = sprintf("%0.2f", quantile(bmi, 0.25)) ,
    median = sprintf("%0.2f", quantile(bmi, 0.50)) ,
    q3 = sprintf("%0.2f", quantile(bmi, 0.75)) ,
    max = max(bmi)
)

ggplot(bmi_adol_men, aes(y = bmi ) ) +
  geom_boxplot(width = 0.5) +
    scale_x_continuous(labels = NULL) +
    labs(y = "BMI",       
         x = "", title = "bmi for 50 adolescent men", subtitle = "Baldi and Moore chapter 23") +
  theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5))

```

```{r normal quantile plot and Shapiro-Wilk test}

qqnorm(bmi_adol_men$bmi, frame = FALSE,
       main = "normal quantile plot adolescent men",
       xlab = "normal scores", ylab = "BMI")
qqline(bmi_adol_men$bmi)

# we will discuss the Shapro-Wilk test in Week 5

shapiro.test(bmi_adol_men$bmi)

```

```{r mean, std dev, std error, conf interval, test}

# calculate and save mean and se 
mean_bmi = mean(bmi_adol_men$bmi)
std_dev_bmi = sd(bmi_adol_men$bmi)
se_bmi <- sd(bmi_adol_men$bmi) / sqrt(50)

# get t* value for 95% confidence interval
t_star_95 <- qt(.975, df = 49, lower.tail = TRUE)

#calculate 95% confidence interval 
lower_limit <- mean_bmi - t_star_95 * se_bmi
upper_limit <- mean_bmi + t_star_95 * se_bmi

# normal quantile plot using ggplot

ggplot(bmi_adol_men, aes(sample = bmi)) +
  geom_qq() + geom_qq_line() +
  labs(title = "bmi for 50 adolescent men") +
  theme(plot.title = element_text(hjust = 0.5))

# print mean, std dev, se, and confidence interval
c(mean_bmi, std_dev_bmi, se_bmi)
c("t* for 49 df, conf level = .95", round(t_star_95,3) )
c(lower_limit, upper_limit)

# use epi.conf from epiR to calculate 95% confidence interval
epi.conf(bmi_adol_men$bmi, ctype = "mean.single", conf.level = 0.95)

```

``` {r 99% confidence interval}

# this part of the analysis is "commented out"
# left here for reference

# get t* for 99% conf int
# t_star_99 <- qt(.005, df = 49, lower.tail = FALSE)
#c("t* for 49 df, conf level = .99", round(t_star_99,3) )

# use epi.conf from epiR to calculate 99% confidence interval
# epi.conf(bmi_adol_men$bmi, ctype = "mean.single", conf.level = 0.99)

```

``` {r Shapiro-Wilk test and t test for Week 5}

t.test(bmi_adol_men$bmi, mu = 26.5 , alternative = "two.sided"  , conf.level = .95)

shapiro.test(bmi_adol_men$bmi)

```